# Generated by Django 4.2 on 2026-02-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester_offered',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Both', 'Both')], default='Both', max_length=20),
        ),
    ]
