# Generated by Django 4.2 on 2026-02-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_student_gpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedcourse',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
