# Generated by Django 4.2 on 2026-03-02 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_completedcourse_completion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='completedcourse',
            name='date_completed',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='degreerequirement',
            name='requirement_type',
            field=models.CharField(choices=[('REQUIRED', 'Required Course'), ('ELECTIVE', 'Elective'), ('CORE', 'Core Course')], max_length=20),
        ),
    ]
