# Generated by Django 4.2 on 2026-03-02 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_student_user_alter_completedcourse_date_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_credits_per_semester', models.IntegerField(default=15)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='courses.student')),
            ],
        ),
        migrations.CreateModel(
            name='PinnedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_label', models.CharField(max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_courses', to='courses.studentpreference')),
            ],
            options={
                'unique_together': {('preference', 'course')},
            },
        ),
    ]
