# Generated by Django 4.2 on 2026-03-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_studentpreference_pinnedcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='concentration',
            field=models.CharField(blank=True, choices=[('', 'No Concentration'), ('AI', 'Artificial Intelligence & Machine Learning'), ('WEB', 'Full Stack Web Development'), ('CYBER', 'Cybersecurity')], default='', max_length=10),
        ),
    ]
