# Generated by Django 4.2 on 2026-03-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_student_concentration'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpreference',
            name='priority',
            field=models.CharField(choices=[('BALANCED', 'Balanced'), ('GEN_ED_FIRST', 'General Education First'), ('CS_FIRST', 'CS Courses First')], default='BALANCED', max_length=20),
        ),
    ]
