# Generated by Django 4.2 on 2026-04-07 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_studentpreference_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentElective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electives', to='courses.student')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
